keycloak.server-url=http://localhost:8181
keycloak.realm=e-commerce-realm
keycloak.client-id=e-commerce-client
keycloak.client-secret=pWfGgonaiZdsU9hz1UOjSHNQBCIOBZ5D

spring.application.name=user-service
server.port=0
server.address=0.0.0.0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgres://localhost:5432/e-commerce-user-service
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
logging.level.com.example=INFO

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/e-commerce-realm

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/