spring.application.name=product-service
server.port=0
server.address=0.0.0.0

eureka.instance.prefer.ip-address=false
eureka.instance.hostname=localhost

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce-product-service
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.root=INFO
logging.level.com.example=INFO